apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: url-shortener-alerts
  labels:
    release: kps
spec:
  groups:
  - name: UygulamaAlarmlari
    rules:
    - alert: UygulamaCoktu
      expr: absent(up{job="url-shortener"})
      for: 1m
      labels:
        severity: critical
        namespace: default
      annotations:
        summary: "URL Kısaltıcı Uygulaması Yanıt Vermiyor!"